image: ubuntu/disco
sources:
- https://git.sr.ht/~eigenhombre/smallscheme
tasks:
- installpip: |
    sudo apt-get -qq install python-pip
- pythondeps: |
    cd smallscheme
    export PATH=$PATH:$HOME/.local/bin
    pip install -q -r requirements.txt
- nosetests: |
    cd smallscheme
    export PATH=$PATH:$HOME/.local/bin
    python -V
    nosetests -vs
