image: ubuntu/lts
sources:
- https://git.sr.ht/~eigenhombre/smallscheme
tasks:
- installpip: |
    sudo apt-get -qq install python3-pip
- nosetests: |
    cd smallscheme
    export PATH=$PATH:$HOME/.local/bin
    pip3 install -q -r requirements.txt
    nosetests -vs
    pycodestyle .
