name: PyPITest

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and test
        run: docker -f Dockerfile.piptest build -t smallscheme-pip-test .
