name: Test

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version:
          - "3.5"
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11.0-alpha - 3.11.0"
          - "pypy-3.6"
          - "pypy-3.7"
          - "pypy-3.8"
          - "pypy-3.9"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
